name: "Create Release with APK"
branding:
  icon: "package"
  color: "red"
description: "Build & Publish APK on Github"
author: "yurakurets"
inputs:
  GITHUB_TOKEN:
    required: true
    description: "Github secret token to allow automated publishing of APK to release."
  REPO_BRANCH:
    required: false
    description: "Github repository branch name."
  APP_FOLDER:
    required: true
    description: "App folder."
  APK_FOLDER:
    required: true
    description: "Apk folder."
  RELEASE_TITLE:
    required: true
    description: "Release title."
runs:
  using: "docker"
  image: "Dockerfile"
